mongodb:
  image: mongo:3.0.4
  container_name: mongo-dev
  volumes:
      - /data/db
  ports:
    - "27018:27017"
  command: mongod --smallfiles

tone-analyzer:
  image: mozammal/tone-analyzer
  container_name: web-tone-analyzer
  ports:
    - "8080:8080"
  links:
    - mongodb
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/tone-analyzer